name: Update application version
description: |
  Update the application version in a file by extracting the version from
  github.head_ref, e.g. release/v1.2.1 would set the version to 1.2.1.
  The version will only be updated on a line that containes "VERSION".
inputs:
  file:
    description: File path to modify
  ref_name:
    description: Ref to extract the version from, e.g. release/v1.2.1
runs:
  using: composite
  steps:
  - name: Update version
    shell: bash -el {0}
    run: |
      set -ex
      version=$(echo "${{ inputs.ref_name }}" | sed -e 's+release/v++g')
      echo "Setting version to $version in ${{ inputs.file }}"
      sed -i -E "/VERSION/s/[0-9]+\.[0-9]+\.[0-9]+/$version/g" ${{ inputs.file }}
      echo "VERSION=$version" >> $GITHUB_OUTPUT
