name: pre-release

on:
  push:
    branches: [main]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Package application
      run: |
        python -m pip install --upgrade pip
        python -m pip install externals/* --upgrade --target build
        python -m pip install . --upgrade --target build
        python -m zipapp build -m "parity_scripter:main" -p "/usr/bin/env python3" -c -o parity_scripter.pyz
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE
          parity_scripter.pyz
