name: release

on:
  pull_request:
    types: [opened]
    branches: [main]
  push:
    branches: [main]

jobs:
  update-version:
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/v')
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update and push version
      uses: ./.github/actions/update-version
      id: update_version
      with:
        file: src/parity_scripter/about.py
        ref_name: ${{ github.head_ref }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "ci: Updated app version to ${{ steps.update_version.outputs.VERSION }}"

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Package application
      id: package
      uses: ./.github/actions/package-app
      with:
        app-name: parity_scripter
        entrypoint: main
        python-version: "3.9"
    - name: Get version
      id: version
      run: echo "VERSION=$(python parity_scripter.pyz --version)" >> $GITHUB_OUTPUT
    - name: Create Release
      if: contains( github.event.head_commit.message, 'release/' )
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ steps.version.outputs.VERSION }}
        tag_name: v${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          LICENSE
          ${{ steps.package.outputs.APP }}
    - name: Create Pre-Release
      uses: softprops/action-gh-release@v1
      with:
        name: Development Build
        tag_name: latest
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          LICENSE
          ${{ steps.package.outputs.APP }}
