name: tagged-release

on:
  push:
    tags: ["v*"]

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - uses: pocket-apps/action-update-version@v1
      with:
        files: parity_scripter/about.py
        version-regexp: '\d+.\d+.\d+'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Package application
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m zipapp parity_scripter -m "parity_scripter:main" -p "/usr/bin/env python3" -c
    - uses: "marvinpinto/action-automatic-releases@v1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          parity_scripter.pyz
