name: tagged-release

on:
  push:
    tags: ["v*"]

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Update application version based on tag
      run: |
        set -ex
        version=$(echo "${{github.ref_name}}" | sed -e 's/v//g')
        echo "Setting parity_scripter/about.py version to $version"
        sed -i -E "/VERSION/s/[0-9]+\.[0-9]+\.[0-9]+/$version/g" parity_scripter/about.py
    - uses: EndBug/add-and-commit@v9.1.3 # You can change this to use a specific version.
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        pathspec_error_handling: exitImmediately
        add: parity_scripter/about.py
        message: "ci: Updated application version and pushed tag"
        push: origin HEAD:refs/heads/main --set-upstream
        tag: ${{github.ref_name}} --force
        tag_push: --force
    - name: Package application
      run: |
        python -m pip install --upgrade pip
        python -m pip install . --upgrade --target build
        python -m zipapp build -m "parity_scripter:main" -p "/usr/bin/env python3" -c -o parity_scripter.pyz
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          parity_scripter.pyz
